;/*FB_PKG_DELIM*/

__d("CometFeedUnitPostRenderingLoggersContext",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=s.createContext({ad_id:null,client_token:null,post_rendering_logger_from_context:void 0});l.default=u}),98);
__d("CometOverlayCloseHandlerContext",["react","react-compiler-runtime"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=e,c=u.useContext,d=u.useEffect,m=s.createContext(null);function p(e){var t=o("react-compiler-runtime").c(4),n=c(m),r,a;t[0]!==e||t[1]!==n?(r=function(){if(!(n==null||e==null)){var t=n(e);return t}},a=[n,e],t[0]=e,t[1]=n,t[2]=r,t[3]=a):(r=t[2],a=t[3]),d(r,a)}l.CometOverlayCloseHandlerContext=m,l.useCometOverlayCloseHandler=p}),98);
__d("DocumentTranslationStatusContext",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=s.createContext(!1);l.default=u}),98);
__d("useDocumentTranslationStatusObserver",["react","react-compiler-runtime"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=s.useEffect,c=s.useState;function d(){var e=o("react-compiler-runtime").c(2),t=c(!1),n=t[0],r=t[1],a,i;return e[0]===Symbol.for("react.memo_cache_sentinel")?(a=function(){var e,t=(e=document)==null?void 0:e.documentElement;if(t!=null){var n=new MutationObserver(function(){t.className.match("translated")?r(!0):r(!1)});return n.observe(t,{attributeFilter:["class"],attributes:!0,characterData:!1,childList:!1}),t.className.match("translated")&&r(!0),(function(){return n.disconnect()})}},i=[],e[0]=a,e[1]=i):(a=e[0],i=e[1]),u(a,i),n}l.default=d}),98);
__d("DocumentTranslationStatusProvider.react",["DocumentTranslationStatusContext","react","react-compiler-runtime","useDocumentTranslationStatusObserver","uuidv4"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=e.useContext;function c(e){var t=o("react-compiler-runtime").c(3),n=e.children,a=r("useDocumentTranslationStatusObserver")(),i;return t[0]!==n||t[1]!==a?(i=s.jsx(r("DocumentTranslationStatusContext").Provider,{value:a,children:n}),t[0]=n,t[1]=a,t[2]=i):i=t[2],i}function d(){"use no memo";var e=u(r("DocumentTranslationStatusContext"));if(e)return r("uuidv4")()}l.DocumentTranslationStatusProvider=c,l.useTranslationKeyForTextParent=d}),98);
__d("ErrorBoundaryForLazyLoad",["cr:38535","react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react"));l.default=n("cr:38535")}),98);
__d("FBNucleusChevronRightFilled16Icon.react",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react"));function u(e){return s.jsxs("svg",babelHelpers.extends({viewBox:"0 0 16 16",width:"1em",height:"1em",fill:"currentColor"},e,{children:[e.title!=null&&s.jsx("title",{children:e.title}),e.children!=null&&s.jsx("defs",{children:e.children}),s.jsx("path",{d:"M5.043 2.043a1 1 0 0 1 1.414 0l1.767 1.763c1.044 1.04 2.08 2.074 3.135 3.136a1.5 1.5 0 0 1-.003 2.117L8.224 12.19l-1.767 1.766a1 1 0 0 1-1.414-1.414l1.768-1.768L9.59 7.998c-.93-.935-1.847-1.848-2.772-2.77l-1.774-1.77a1 1 0 0 1 0-1.415z"})]}))}u.displayName=u.name+" [from "+i.id+"]",u._size=16,u._isSVG=!0;var c=u;l.default=c}),98);
__d("IntlCLDRNumberType02",["IntlVariations"],(function(t,n,r,o,a,i,l){"use strict";var e={getVariation:function(t){return t===0||t===1?r("IntlVariations").NUMBER_ONE:r("IntlVariations").NUMBER_OTHER}},s=e;l.default=s}),98);
__d("IntlCLDRNumberType03",["IntlVariations"],(function(t,n,r,o,a,i,l){"use strict";var e={getVariation:function(t){return t===0||t===1?r("IntlVariations").NUMBER_ONE:r("IntlVariations").NUMBER_OTHER}},s=e;l.default=s}),98);
__d("IntlCLDRNumberType19",["IntlVariations"],(function(t,n,r,o,a,i,l){"use strict";var e={getVariation:function(t){return t===1?r("IntlVariations").NUMBER_ONE:t===0||t!==1&&t%100>=1&&t%100<=19?r("IntlVariations").NUMBER_FEW:r("IntlVariations").NUMBER_OTHER}},s=e;l.default=s}),98);
__d("IntlCLDRNumberType26",["IntlVariations"],(function(t,n,r,o,a,i,l){"use strict";var e={getVariation:function(t){return t===1?r("IntlVariations").NUMBER_ONE:t%10>=2&&t%10<=4&&(t%100<12||t%100>14)?r("IntlVariations").NUMBER_FEW:r("IntlVariations").NUMBER_MANY}},s=e;l.default=s}),98);
__d("RtiRequestStreamQosFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("8530"),s=o("FalcoLoggerInternal").create("rti_request_stream_qos",e),u=s;l.default=u}),98);
__d("SidneeAbrConfigDefaults",[],(function(t,n,r,o,a,i){"use strict";var e=5e3,l="0,1,1; 80,1.5,1.3; 97,2.0,1",s=1,u=65,c=1,d=5e3,m=3e4,p=2,_="0,1,1.4; 100,2,1",f=1,g=3e4,h=1.7,y=80,C=1.3,b=1.5,v=1.85,S=50,R=.5,L=4,E="-1,2,1; 0,1.7,2; 1,1",k=1,I=4,T=2;i.avgSegmentDurationMsDefault=e,i.badUploadQualityRewardCurveDefault=l,i.badUploadQualityRewardCurveFallbackDefault=s,i.badUploadQualityThresholdDefault=u,i.bitrateMultiplierDefault=c,i.bufferReductionMsDefault=d,i.defaultVideoDurationMsDefault=m,i.encodingRiskDefault=p,i.goodUploadQualityRewardCurveDefault=_,i.goodUploadQualityRewardCurveFallbackDefault=f,i.lookAheadMsDefault=g,i.maxAggressiveRiskDefault=h,i.maxBandwidthConfidencePctDefault=y,i.maxConservativeRiskDefault=C,i.maxNormalRiskDefault=b,i.maxVeryAggressiveRiskDefault=v,i.minBandwidthConfidencePctDefault=S,i.minBitrateMultiplierDefault=R,i.rewardRatioRoundDigitsDefault=L,i.riskCurveDefault=E,i.riskCurveFallbackDefault=k,i.riskRatioRoundDigitsDefault=I,i.riskRewardRatioRoundDigitsDefault=T}),66);
__d("VideoPlayerNextgendashLoggingDestinationFBLogger",["nextgendasherr"],(function(t,n,r,o,a,i,l){"use strict";function e(){return{displayName:"VideoPlayerNextgendashLoggingDestinationFBLogger",log:function(t,n){switch(n.type){case"generic_error":{var e;(e=o("nextgendasherr").nextgendasherrFBLogger(t).catching(n.error)).mustfix.apply(e,[n.error.messageFormat].concat(n.error.messageParams));break}case"generic_error_as_warning":{var r;(r=o("nextgendasherr").nextgendasherrFBLogger(t).catching(n.error)).warn.apply(r,[n.error.messageFormat].concat(n.error.messageParams));break}case"generic_warning":{var a,i;(a=o("nextgendasherr").nextgendasherrFBLogger(t)).warn.apply(a,[n.format].concat(((i=n.params)!=null?i:[]).map(function(e){return String(e)})));break}}}}}l.createVideoPlayerNextgendashLoggingDestinationFBLogger=e}),98);
__d("VideoPlayerRetryConfig",[],(function(t,n,r,o,a,i){"use strict";var e=Object.freeze({backoffMultiplier:2,initialDelayMs:200,jitterPercent:.2,maxDelayMs:8e3,retryBehavior:"exponential",retryCount:5}),l=Object.freeze({retryBehavior:"linear",retryCount:20,retryDelayMs:2e3}),s=Object.freeze({backoffMultiplier:2,initialDelayMs:200,jitterPercent:.2,maxDelayMs:2e3,retryBehavior:"exponential",retryCount:2}),u=Object.freeze({retryBehavior:"linear",retryCount:2,retryDelayMs:2e3}),c=Object.freeze({backoffMultiplier:1.5,initialDelayMs:1e3,jitterPercent:.3,maxDelayMs:3e4,retryBehavior:"exponential",retryCount:Number.POSITIVE_INFINITY}),d=Object.freeze({retryBehavior:"linear",retryCount:Number.POSITIVE_INFINITY,retryDelayMs:5e3}),m=e;function p(e){return e==="URL_RESPONSE_HTTP_429"||e==="URL_RESPONSE_HTTP_503"||e==="URL_RESPONSE_HTTP_504"}function _(e,t){t===void 0&&(t=m);var n=t.initialDelayMs*Math.pow(t.backoffMultiplier,e),r=n*t.jitterPercent,o=n+(Math.random()*2-1)*r;return Math.min(o,t.maxDelayMs)}function f(e,t){if(t===void 0&&(t=m),e==null)return null;var n=e.trim();if(n==="")return null;if(/^\d+$/.test(n)){var r=Number(n);return Math.min(r*1e3,t.maxDelayMs)}if(!/[A-Za-z]/.test(n))return null;var o=Date.parse(n);if(!Number.isFinite(o))return null;var a=Math.max(0,o-Date.now());return Math.min(a,t.maxDelayMs)}function g(t){return t?{fetchRejection:e,httpNotOk:e,httpNotOkUnrecoverable:s,offline:c,responseDataFailed:e}:{fetchRejection:l,httpNotOk:l,httpNotOkUnrecoverable:u,offline:d,responseDataFailed:l}}i.PROGRESSIVE_RETRY_CONFIG=m,i.isRetriableTransientHttpResponseErrorName=p,i.computeBackoffMs=_,i.parseRetryAfterMs=f,i.getFetchedResourceRetryConfig=g}),66);
__d("VideoPlayerWatchInlineEndScreen_info$normalization.graphql",[],(function(t,n,r,o,a,i){"use strict";var e=(function(){var e={alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null},t=[e];return{kind:"SplitOperation",metadata:{},name:"VideoPlayerWatchInlineEndScreen_info$normalization",selections:[{alias:null,args:null,kind:"ScalarField",name:"video_chaining_caller",storageKey:null},{alias:null,args:null,kind:"ScalarField",name:"video_channel_entry_point",storageKey:null},{alias:null,args:null,concreteType:"Video",kind:"LinkedField",name:"video",plural:!1,selections:[e,{alias:null,args:null,kind:"ScalarField",name:"can_viewer_share",storageKey:null},{alias:null,args:null,concreteType:"Story",kind:"LinkedField",name:"creation_story",plural:!1,selections:[{alias:null,args:null,concreteType:null,kind:"LinkedField",name:"shareable",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"__typename",storageKey:null},{alias:"wwwUrl",args:[{kind:"Literal",name:"site",value:"www"}],kind:"ScalarField",name:"url",storageKey:'url(site:"www")'},{kind:"InlineFragment",selections:t,type:"Node",abstractKey:"__isNode"},{kind:"InlineFragment",selections:t,type:"XFBTopicTag",abstractKey:null}],storageKey:null},e],storageKey:null}],storageKey:null}]}})();a.exports=e}),null);
__d("focusKeyboardEventPropagation",[],(function(t,n,r,o,a,i){"use strict";function e(e){return e._stopFocusKeyboardPropagation===!0}function l(e){e._stopFocusKeyboardPropagation=!0}i.hasFocusKeyboardEventPropagationStopped=e,i.stopFocusKeyboardEventPropagation=l}),66);
__d("ghlTestUBTNoOp",[],(function(t,n,r,o,a,i){"use strict";var e=function(t){},l=e;i.default=l}),66);
__d("react-relay/relay-hooks/useMutationAction_EXPERIMENTAL",["Promise","react","react-compiler-runtime","react-relay/relay-hooks/useRelayEnvironment","relay-runtime"],(function(t,n,r,o,a,i){"use strict";var e,l,s=n("react-compiler-runtime").c,u=e||(e=n("react")),c=n("relay-runtime").commitMutation,d=u.useCallback;function m(e){var t=s(4),r=n("react-relay/relay-hooks/useRelayEnvironment")(),o,a;t[0]!==r||t[1]!==e?(o=function(o){return new(l||(l=n("Promise")))(function(t,n){c(r,{mutation:e,variables:o,onCompleted:function(n){t(n)},onError:function(t){n(t)}})})},a=[r,e],t[0]=r,t[1]=e,t[2]=o,t[3]=a):(o=t[2],a=t[3]);var i=d(o,a);return i}a.exports=m}),null);
__d("relay_provider_comet_ufi_ssr_seo_defer.relayprovider",["gkx"],(function(t,n,r,o,a,i,l){"use strict";var e={get:function(){return!r("gkx")("25904")}};l.default=e}),98);